import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "./globals.css";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://chat-anywhere.vercel.app";

export const viewport: Viewport = {
  themeColor: "#075E54",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "Chat-Anywhere — Instant Chat Rooms, No Signup Required",
    template: "%s | Chat-Anywhere",
  },
  description:
    "Create or join instant chat rooms with just a URL. No signup, no data storage, no tracking. Real-time messaging with image sharing and link previews. Private, fast, and free.",
  keywords: [
    "chat",
    "real-time chat",
    "instant messaging",
    "anonymous chat",
    "no signup chat",
    "chat rooms",
    "group chat",
    "private chat",
    "web chat",
    "online chat",
    "whatsapp style chat",
    "browser chat",
  ],
  authors: [{ name: "Chat-Anywhere" }],
  creator: "Chat-Anywhere",
  publisher: "Chat-Anywhere",
  applicationName: "Chat-Anywhere",
  category: "Communication",

  // Open Graph — auto-generated by /opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Chat-Anywhere",
    title: "Chat-Anywhere — Instant Chat Rooms, No Signup Required",
    description:
      "Create or join instant chat rooms with just a URL. No signup, no data storage, no tracking. Real-time messaging with image sharing and link previews.",
    url: BASE_URL,
  },

  // Twitter — auto-generated by /opengraph-image.tsx
  twitter: {
    card: "summary_large_image",
    title: "Chat-Anywhere — Instant Chat Rooms",
    description:
      "Create or join instant chat rooms with just a URL. No signup, no data storage.",
    creator: "@chatanywhere",
  },

  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Icons
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-192.svg", sizes: "192x192", type: "image/svg+xml" },
      { url: "/icon-512.svg", sizes: "512x512", type: "image/svg+xml" },
    ],
    apple: [{ url: "/apple-icon.svg", sizes: "180x180", type: "image/svg+xml" }],
  },

  // PWA
  manifest: "/manifest.webmanifest",

  // Additional
  referrer: "origin-when-cross-origin",
  formatDetection: {
    telephone: false,
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Chat-Anywhere",
  },
  other: {
    "google-site-verification": "optional-add-your-verification-code-here",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href={BASE_URL} />
        <script dangerouslySetInnerHTML={{
          __html: `
            try {
              var t = localStorage.getItem('theme');
              if (t === 'dark' || (!t && matchMedia('(prefers-color-scheme:dark)').matches)) {
                document.documentElement.classList.add('dark');
              }
            } catch(e) {}
          `
        }} />
      </head>
      <body className="h-[100dvh] overflow-hidden">
        {/* JSON-LD Structured Data */}
        <Script
          id="schema-structured-data"
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              name: "Chat-Anywhere",
              url: BASE_URL,
              description:
                "Create or join instant chat rooms with just a URL. No signup, no data storage, no tracking.",
              applicationCategory: "Communication",
              operatingSystem: "All",
              browserRequirements:
                "Requires JavaScript. Supports all modern browsers.",
              offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "USD",
              },
              author: {
                "@type": "Organization",
                name: "Chat-Anywhere",
              },
            }),
          }}
        />
        {children}
      </body>
    </html>
  );
}
